default : &DEFAULT

  verbose: True
  device: "cuda:1"
  seed: 42

  data:
    folder: "../IJEPA/data/Model_II/"
    train_split: 0.8
    val_split: 0.1
    batch_size: 64
    shuffle: False

  enc:
    img_size: 64
    patch_size: 16
    in_chs: 1
    emb_dim: 192 #384 #192
    depth: 6 #12 #6 #6
    num_head: 8
    mask_ratio: 0.75 #0.10 #0.75

  dec:
    emb_dim: 192 #384 #192
    depth: 2 #4 # 2 #2
    num_head: 8
    mlp_ratio: 4
    
  train:
    lr: 0.001
    epochs: 50